from tkinter import *
root=Tk()
Label(root,text="ITVoyagers Registration Form",bg="blue",fg="white",font="arial 20 italic bold").grid(row=0,columnspan=8,sticky=W)
label=Label(root,text="Name of visitor",height=2,width=15,fg='blue',font="verdana")
label.grid(row=1,column=1,sticky=W)
w=Entry(root)
w.grid(row=1,column=2)
label=Label(root,text="Favourite programming language",height=2,width=25,fg="blue",font="BOLD")
label.grid(row=2,column=1,sticky=W)
w=Entry(root)
w.grid(row=2,column=2)
label=Label(root,text="Gender",height=2,width=20,fg="blue",font="verdana")
label.grid(row=3,column=1,sticky=W)
var=IntVar()
w=Radiobutton(root,text="Male",variable=var,value=1,command="selection")
w.grid(row=3,column=2,sticky=N)
w=Radiobutton(root,text="Female",variable=var,value=2,command="selection")
w.grid(row=4,column=2,sticky=N)
label=Label(root,text="Address",height=5,width=15,fg="blue",font="verdana")
label.grid(row=5,column=1,sticky=W)
w=Text(root,height=5,width=15,relief=RAISED)
w.insert(INSERT,"Edit Here")
w.grid(row=5,column=2,sticky=N)
label=Label(root,text="Email id",height=2,width=15,fg="blue",font="verdana")
label.grid(row=6,column=1,sticky=W)
w=Entry(root)
w.grid(row=6,column=2,sticky=N)
label=Label(root,text="Contact info",height=2,width=15,fg="blue",font="verdana")
label.grid(row=7,column=1,sticky=W)
w=Entry(root)
w.grid(row=7,column=2,sticky=N)
label=Label(root,text="Country",height=2,width=15,fg="blue",font="verdana")
label.grid(row=8,column=1,sticky=W)
w=Entry(root)
w.grid(row=8,column=2,sticky=N)
label=Label(root,text="State",height=2,width=15,fg="blue",font="verdana")
label.grid(row=9,column=1,sticky=W)
w=Entry(root)
w.grid(row=9,column=2,sticky=E) 
label=Label(root,text=  "Select Topic You Wish To Learn",height=2,width=25,fg="blue",font="BOLD")
label.grid(row=10,column=1,sticky=N)
Var1=IntVar()
Var2=IntVar()
w1=Checkbutton(root,text="Python",variable=Var1)
w1.grid(row=10,column=2,sticky=N)
w2=Checkbutton(root,text="Business Intelligence",variable=Var2)
w2.grid(row=11,column=2,sticky=N)
b=Button(root,text="REGISTER HERE", height=1, width=15, bg="blue", fg="White",font="Verdana 12")
b.grid(row=12,columnspan=5)
